### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [jakeb072001/TerraCraft#16] opened 2024-05-27 04:42 UTC
[latest.log](https://github.com/jakeb072001/TerraMine/files/15450873/latest.log)
1
[crash-2024-05-27_12.38.43-client.txt](https://github.com/jakeb072001/TerraMine/files/15450875/crash-2024-05-27_12.38.43-client.txt)

**Comment by jakeb072001** [comment] 2024-05-27 13:34
hmm, not exactly sure the cause of the issue. I can add a null check for the next update which should prevent crashing but I'm not sure why the player is returning null, I assume another mod is doing something to cause this.

**Comment by jakeb072001** [comment] 2024-05-27 14:43
may be fixed in 1.7.4, give it a shot when you can.

**Closed as completed** 2024-09-18 03:13 UTC
Labels: bug
